general {
    hide_cursor = true
}

background {
    path = ~/dotfiles/assets/wallpaper.jpg
    blur_passes = 3
    blur_size = 8
}

label {
    text = $TIME
    font_size = 80

    position = 0, 200
    halign = center
    valign = center
}

label {
    text = $DESC
    font_size = 24

    position = 0, 120
    halign = center
    valign = center
}

input-field {
    size = 300, 60

    outer_color = rgba(33ccffee)
    inner_color = rgba(0,0,0,0.4)

    font_color = rgb(ffffff)

    position = 0, -100
    halign = center
    valign = center

    placeholder_text = Password...
}
